### ISSUE TITLE
[Feature Request] use plug.kak format

### ISSUE THREAD

**Issue by jtrv** [occivink/kakoune-find#10]
Great work on this plugin! I am creating this issue for the consideration of using the [plug.kak](https://github.com/andreyorst/plug.kak) format so that this plugin is manageable from the plugin-manager.

**Comment by occivink** [comment]
Where is the format documented? I had thought that plug.kak could handle this simple structure.

**Comment by jtrv** [comment]
My apologies I made an assumption because the find command wasn't working after I installed it with plug.kak and the project did not share the `rc/` directory like other plugins when I checked the repo. It looks like the issue was actually another conflict with [kakoune.cr](https://github.com/alexherbo2/kakoune.cr/blob/5edd5d51667243f926ff2a90a0bc2cf4108b671b/share/kcr/rc/lib.kak#L19). Closing this issue out.
