### ISSUE TITLE
can't apply any change neither with find nor with grep buffers

### ISSUE THREAD

**Issue by andreyorst** [occivink/kakoune-find#2]
It doesn't display any error, just echoes that 0 changes were applied and all failed. I just open buffers and change some text through `find`, and confirm it with `find-apply-changes`.

**Comment by occivink** [comment]
Did you update the script? I made some recent changes to adapt to the persistent register history

edit: oh nevermind, I forgot to push them

**Comment by andreyorst** [comment]
Yeah, now it works. Thanks!
