### ISSUE TITLE
WinCreate hook doesnt run for *find* buffer

### ISSUE THREAD

**Issue by SolitudeSF** [occivink/kakoune-find#9]

**Comment by occivink** [comment]
mh I presume this is because of the `eval no-hook`. I did that to avoid running too many hooks when doing the `eval -buffer *` but I think we can just move the flag.

**Comment by SolitudeSF** [comment]
moving `-no-hooks` to inner eval works

**Comment by SolitudeSF** [comment]
maybe adding another inner eval for -no-hooks, so hooks wont run only for `*find-tmp*`

**Comment by occivink** [comment]
I think those do not happen, since *find-tmp* is a debug buffer. In any case, BufCreate is not fired for it.
